# Generated by Django 4.2.2 on 2023-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Job_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Remote', 'Remote')], max_length=15)),
            ],
        ),
    ]
