# Generated by Django 4.2.2 on 2023-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to=None)),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
