# Generated by Django 4.2.2 on 2023-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_apply_created_at_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to='apply/'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
