# Generated by Django 4.2.2 on 2023-08-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
