# Generated by Django 4.2.2 on 2023-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0011_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/%y/%m/%d'),
        ),
    ]
